from fpdf import FPDF
from datetime import datetime


def generate_pdf_report(score, risk_level, findings_df):
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(
        200,
        10,
        "Firewall Security Audit Report",
        ln=True,
        align="C"
    )

    pdf.ln(5)

    # Metadata
    pdf.set_font("Arial", "", 11)

    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    pdf.cell(
        200,
        8,
        f"Generated On: {current_time}",
        ln=True
    )

    pdf.cell(
        200,
        8,
        "Generated By: Satyabrata Behera",
        ln=True
    )

    pdf.ln(8)

    # Summary Section
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        200,
        10,
        "Security Summary",
        ln=True
    )

    pdf.set_font("Arial", "", 12)

    pdf.cell(
        200,
        8,
        f"Security Score: {score}/100",
        ln=True
    )

    pdf.cell(
        200,
        8,
        f"Risk Level: {risk_level}",
        ln=True
    )

    pdf.cell(
        200,
        8,
        f"Total Issues Found: {len(findings_df)}",
        ln=True
    )

    pdf.ln(8)

    # Recommendations Section
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        200,
        10,
        "Top Recommended Actions",
        ln=True
    )

    pdf.set_font("Arial", "", 11)

    recommendations = findings_df["Recommendation"].unique()

    for i, rec in enumerate(recommendations[:5], 1):
        pdf.multi_cell(
            0,
            8,
            f"{i}. {rec}"
        )

    pdf.ln(5)

    # Findings Summary
    pdf.set_font("Arial", "B", 14)
    pdf.cell(
        200,
        10,
        "Findings Summary",
        ln=True
    )

    pdf.set_font("Arial", "", 10)

    for _, row in findings_df.head(10).iterrows():
        pdf.multi_cell(
            0,
            7,
            f"Rule ID: {row['RuleID']} | "
            f"Issue: {row['Issue']} | "
            f"Severity: {row['Severity']}"
        )

    # Save File
    file_path = "firewall_audit_report.pdf"
    pdf.output(file_path)

    return file_path
